### ISSUE TITLE
[PE-D][Tester A] Cant understand UG difference

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W08-2/tp#110]
I cant seem to tell the difference between totalScore and totalscore 

![image.png](https://raw.githubusercontent.com/Nid21cs/ped/main/files/0c4b5443-0775-40a9-a207-d00fe836f2fb.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Nid21cs/ped#3

**Comment by seraphimstreets** [comment]
Make it clearer in UG
