### ISSUE TITLE
[PE-D][Tester C] stats does not give feedback on unfound inputs

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W08-2/tp#139]
![image.png](https://raw.githubusercontent.com/howenc/ped/main/files/8a1664ea-53bc-45ac-8147-b54965de5e3d.png)

No feedback is given when there is no tutorial group found with that name.

This can be a problem when there are too many tutorials to keep track off, like in CS1101S where every tutorial has only 7-10 students.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: howenc/ped#9

**Comment by siqirua** [comment]
Bug fixed.
