### ISSUE TITLE
[PE-D][Tester C] compStats format is different from documentation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W08-2/tp#140]
![image.png](https://raw.githubusercontent.com/howenc/ped/main/files/9152efcc-5382-471a-8b65-d607010f166e.png)

`compStats` itself is an invalid command format even though all the arguments are optional

![image.png](https://raw.githubusercontent.com/howenc/ped/main/files/c5b208d1-6e3b-4205-8716-c753a63f4832.png)

As seen in the UG, it has `[c/COMP_NAME]`, the square brackets mean that the field is optional.

However in testing, it is shown that the `[c/COMP_NAME]` argument is actually required.

![image.png](https://raw.githubusercontent.com/howenc/ped/main/files/84583948-8ecd-405e-b073-ed8d46e10a07.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: howenc/ped#10

**Comment by siqirua** [comment]
Bug fixed.
