### ISSUE TITLE
[PE-D][Tester C] compStats does not give feedback on unfound inputs

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W08-2/tp#141]
![image.png](https://raw.githubusercontent.com/howenc/ped/main/files/6d348f42-e917-424e-9ba3-90269aa8e9fd.png)

`compStats c/test` will not find any stats as there is no comp with name test. 
However, the command does not execute anything and does not throw error.
This can be a problem when there are too many comps and the user is not able to effectively keep track of all of them.
Some feedback should be given to the user to let them know that there is no such comp found.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: howenc/ped#11

**Comment by siqirua** [comment]
Bug fixed.
