### ISSUE TITLE
[Feature Flaw?] Too many dp kept for student score

### ISSUE THREAD

**Issue by siqirua** [AY2324S1-CS2103T-W08-2/tp#179]
![image](https://github.com/AY2324S1-CS2103T-W08-2/tp/assets/43068307/71431347-6bf9-4e15-8a09-b620b8ead0fc)
Not sure if we want to keep so many dp
In addition, the number is wrong, should be 36.5555556 instead of 36.555557

**Comment by seraphimstreets** [comment]
Included in UG: Users advised not to input more than 2dp
